# Generated by Django 5.1.2 on 2024-11-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_discount_percentage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discount',
        ),
        migrations.RemoveField(
            model_name='producttag',
            name='product',
        ),
        migrations.AddField(
            model_name='cart',
            name='coupon_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.DeleteModel(
            name='ProductTag',
        ),
    ]
