# Generated by Django 5.1.2 on 2024-11-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_delete_discount_remove_producttag_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='coupon_discounted_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
