# Generated by Django 5.1.2 on 2024-11-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_cart_coupon_discounted_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='coupon_discounted_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
